### PR TITLE
ore parity

### PR DESCRIPTION
**Pull request by SilkRose**
#### What is this PR for?

Adds parity to all the ores, so they all have 6 textures each.
- 2 emerald ore variants.
- 2 deepslate emerald ore varients.

- [x] **I have made and am willing to license my contribution under the MIT license, or have permission from the original author to license it under MIT.**

### CODE REVIEW

**Comment by meadowsys** [comment]
i'll take over this and add two for deepslate too, if that's alright

**Comment by SilkRose** [comment]
> i'll take over this and add two for deepslate too, if that's alright

Sure.

**Comment by meadowsys** [comment]
right, need to add for deepslate too

**Review by meadowsys — APPROVED** [review]
I say stone part looks good, @velvetremedy in private said my deepslate part looks good

**Pull request merged**
