### PR TITLE
Other guis

### PR DESCRIPTION
**Pull request by PCelestia**

### CODE REVIEW

**Comment by Sollace** [comment]
Please rebase your branch. I'm seeing a lot of unrelated changes in there.

**Comment by PCelestia** [comment]
its saying current branch other-guis is up to date

**Comment by Sollace** [comment]
@PCelestia Why are there block textures in your guis PR, then?

**Comment by PCelestia** [comment]
the only blocks present are the honey block and the honeycomb block, and they are there because they aren't currently present in the resourcepack, and aren't worth adding them via separate pr.

**Pull request merged**
