### PR TITLE
houskeepin'

### PR DESCRIPTION
**Pull request by autumnblazey**
PR does many random things to clean up the repository and add some of Github's community health files

List of things that get done (add to this as commits come in):

- fix eq language
- README updates
- contributing
- issue and pr templates
- how to get support

### CODE REVIEW

**Comment by autumnblazey** [comment]
I think I want to squash merge this when done

**Comment by autumnblazey** [comment]
goal: finish today™

**Comment by autumnblazey** [comment]
@VelvetRemedy is also very involved im not taking all the credit

**Review by VelvetRemedy — APPROVED** [review]
Looks good.

**Pull request merged**
